### ISSUE TITLE
Неканоничное возвращаемое значение

### ISSUE THREAD

**Issue by Sovianum** [rentgen94/QuestGoMail#1]
Идея понятна: ты хочешь возвращать различные ошибки в различных случаях, но в го все-таки принято в такой ситуации возвращать ошибки. Лучше сделать обертку dbErr, для которой реализовать метод (er dbErr) Error() string и сравнивать результаты вызова этой функции.

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L20

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L34

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L48

**Comment by rentgen94** [comment]
Сделал возвращение ошибок, оборачивать в другую функцию не стал.
