### ISSUE TITLE
Некорректная обработка ошибок

### ISSUE THREAD

**Issue by Sovianum** [rentgen94/QuestGoMail#2]
Даже если база сфейлила на абсолютно безобидном запросе, все равно нужно прокидывать ошибку на верх. Fatal и panic везде, кроме тестов и старта программы, под запретом :)

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L65

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L74

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L80

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/playerHandlers.go#L68

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/playerHandlers.go#L71

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/playerHandlers.go#L77

**Comment by rentgen94** [comment]
Убрал все вызовы log.Fatal and panic. Теперь при ошибке в Header кидаю http.StatusInternalError
