### ISSUE TITLE
Копипаста

### ISSUE THREAD

**Issue by Sovianum** [rentgen94/QuestGoMail#3]
В хэндлерах во всех ветвях программы встречается один и тот же код. 
1. Стоит вынести его из ветвления;
2. Возможно, стоит завести приватную функцию, которая проставляет этот заголовок.

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/playerHandlers.go#L21

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/playerHandlers.go#L36

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/playerHandlers.go#L40

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/playerHandlers.go#L54

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/playerHandlers.go#L57

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/playerHandlers.go#L60

**Comment by rentgen94** [comment]
Вынес данную строчку в начало каждого хендлера
