### ISSUE TITLE
Некоррекная обработка ошибок и валидация

### ISSUE THREAD

**Issue by Sovianum** [rentgen94/QuestGoMail#4]
1. Почему ты здесь игноришь ошибку? Этого не стоит делать как минимум потому, что база может просто лежать. И в этом случае нужно возвращть 500 или что-нибудь в этом роде.

2. Вот это длинное логическое выражение в if плохо читается. Лучше сделать отдельный метод (p Player) Equals(another Player) bool

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/playerHandlers.go#L20

**Comment by rentgen94** [comment]
Исправил
