### ISSUE TITLE
Русский язык в коде

### ISSUE THREAD

**Issue by Sovianum** [rentgen94/QuestGoMail#6]
Не стоит

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L12
https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L13
https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L14
https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L15
https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L16
https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L17

**Comment by rentgen94** [comment]
Перевел на английский
