### ISSUE TITLE
Строки запросов в коде

### ISSUE THREAD

**Issue by Sovianum** [rentgen94/QuestGoMail#7]
Здесь я не настаиваю, но имхо, лучше строки запросов выносить в константы, чтобы при дебаге синтаксиса запросов не нужно было лезть в код.

https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L23
https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L35
https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L49
https://github.com/rentgen94/QuestGoMail/blob/36b6d3b4837149cf7bd3c5155cb92d66899ec670/server/database/playerDAO.go#L63

**Comment by rentgen94** [comment]
Перенес в константы
